name: Update Dependencies

on:
  #schedule:
    # Every Monday at 1 AM
    #- cron: '0 1 * * 1'
  push:

jobs:
  Update_Deps:

    runs-on: ubuntu-latest
    name: ${{ matrix.name || matrix.args }}

    strategy:
      fail-fast: false
      matrix:
        args: [docs, flake8]

        # Uncomment to enable base dependency checking
        # include:

        # # - args: '-b'
        # #   name: Base Dependencies

        # - args: '-a -i .*PyYAML'
        #   name: PyYAML deps yo

    env:
      DEPS_UPDATED: false

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PR_DEPLOY_PRIVATE_KEY }}

      - name: Install latest Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install bumpdeps
        run: pip install bumpdeps

      - name: Update deps
        run: |
          set -x
          bumpdeps ${{ matrix.args }}
          git diff --quiet || echo "DEPS_UPDATED=true" >> $GITHUB_ENV

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          PR_BRANCH=bumpdeps/$(echo ${{ matrix.name }} | tr ' ' _)_${{ github.run_id }}
          PR_MSG="BumpDeps: ${{ matrix.name || matrix.args }}"

          # Configure Git
          git config --global user.name "BumpDeps"
          git config --global user.email "<>"

          # Create commit in new branch
          git checkout -b $PR_BRANCH
          git commit -a -m "$PR_MSG"
          git --no-pager log -n 2
          git push -u origin $PR_BRANCH

          # Create PR
          gh pr create -B main -H $PR_BRANCH --title "$PR_MSG" --body "Created by Github Action"
        if: env.DEPS_UPDATED == 'true'
